### ISSUE TITLE
Template defined checkbox value cannot be set on Java constructor

### ISSUE THREAD

**Issue by samulivaadin** [vaadin/vaadin-checkbox-flow#69] opened 2018-08-01 10:08 UTC
Consider that in template there is: 
`<vaadin-checkbox id="failbox">You cant set my value on constructor</vaadin-checkbox>`
And on Java side 
`    @Id("failbox")
    private Checkbox failbox;`

then in Java class constructor value of failbox is set
`failbox.setValue(Boolean.TRUE);`

Would expect that checkbox value is checked but this has no effect.

See example project in attachment. ReviewList.java and reviews-list.html for live demo. Uses Vaadin 10.0.2.

[failbox.zip](https://github.com/vaadin/vaadin-checkbox-flow/files/2249002/failbox.zip)

**Comment by denis-anisimov** [comment] 2018-08-01 10:20
This is a duplicate of #4304.
It's already fixed but not released.

**Closed by denis-anisimov** 2018-08-01 10:20 UTC
