### ISSUE TITLE
setVisible(boolean) not working for checkbox component 

### ISSUE THREAD

**Issue by mimarko** [vaadin/vaadin-checkbox-flow#72] opened 2018-08-15 12:30 UTC
Strange behaviour for set visibility of checkbox component. setVisible(boolean) doesn't work the same as for other components , e.g vaadin-button or vaadin-text-field. Simple sample to reproduce behaviour:
```java
            Checkbox toggle = new Checkbox(true); // using as toggle to set component visibility param
            toggle.setLabel("Show / Hide components");

            Checkbox c = new Checkbox(true); 
            c.setLabel("Checkbox component");

            Button b = new Button("Button component");
            TextField tf = new TextField("Text field component", "Enter here..");

            toggle.addValueChangeListener(e->{
                c.setVisible(toggle.getValue()); // not hide checkbox !!!
                b.setVisible(toggle.getValue());
                tf.setVisible(toggle.getValue());            
            });
```

**Comment by denis-anisimov** [comment] 2018-08-16 06:46
Have you unchecked checkbox on the client side?

The checkbox is created using `true` in its CTOR `Checkbox c = new Checkbox(true); `.
It means it's checked.

If it's not shown as checked then it's another issue (which is may be fixed).

So if it's checked and you have not unchecked it then the behavior is correct since you are passing
`true` to `setVisible`  method and it should be visible.

I'm closing the issue since I cannot reproduce the unexpected behavior and it works for me as it should.

Please reopen if you still see unexpected behavior.

**Closed by denis-anisimov** 2018-08-16 06:46 UTC
Labels: bug

**Comment by mimarko** [comment] 2018-08-16 10:17
Hi Denis,

Could you check again please. If I try to add Checkbox component to any layout container, e.g. Div and if I set initially false (or any other value) and setVisible also to false checkbox will be still visible on page. Here is a point to show/hide component on page (set visibility like on other components (e.g. TextField) ) and not checked/unchecked Checkbox ! There is nothing strange with initial value in CTOR.

Checkout this code:
```java
Checkbox c = new Checkbox(); 
c.setLabel("Checkbox component");
c.setVisible(false); //  setVisible for Checkbox have unexpected behaviour !!!
div.add(c); // Checkbox is visible in Div container (or any other layout) !!
```

**Comment by denis-anisimov** [comment] 2018-08-16 10:44
Still can't reproduce.

Your latest  code is not the same you have shown initially.

Here is the code which I use :

```
Checkbox checkbox = new Checkbox();
checkbox.setLabel("Default Checkbox");

checkbox.setVisible(false);
NativeButton button = new NativeButton("Hide",
                event -> checkbox.setVisible(!checkbox.isVisible()));
```

This code allows to switch visibility.
And the `checkbox` is added into a `Div`.

Initially the `checkbox` is not visible and then its visibility is updated correctly if you click on the the button.

It might be there is a difference in versions which we are using.
Please try the latest SNAPSHOT for Flow and for checkbox.
I cannot reproduce it with SNAPSHOTs.
