### ISSUE TITLE
CheckboxGroup.getElement().setProperty method does not work

### ISSUE THREAD

**Issue by evrenism** [vaadin/vaadin-checkbox-flow#147] opened 2020-05-14 14:31 UTC
I add property to the CheckboxGroup element as follows;
```
CheckboxGroup<SampleClass> checkboxGroup = new CheckboxGroup<>();
checkboxGroup.getElement().setProperty("column", "2");
```
I expect it to work like this;
`<vaadin-checkbox-group column = "2"> ... </vaadin-checkbox-group>`
But the setProperty method does not work.

**Comment by DiegoCardoso** [comment] 2020-05-14 14:45
Can you try using `Element#setAttribute` instead?

**Comment by evrenism** [comment] 2020-05-15 08:54
> Can you try using `Element#setAttribute` instead?
Yes Element #setAttribute definitely works. 

Element#setAttribute or Element#setProperty; does it matter which one we use? Which one is working, should we use it?

**Comment by DiegoCardoso** [comment] 2020-05-15 10:33
They are different and serve different purposes:
- `Element#setProperty` is used when you need to define a property of the HTML DOM element, such as the `value` of an input field or `innerHTML` of an element container, like `<div>`. Setting it doesn't necessarily reflects to an attribute. 
- `Element#setAttribute` is used when you need to add an attribute of the DOM element, which has the similar behaviour as the `Element#setAttribute` API present on the browser.

**Comment by evrenism** [comment] 2020-05-15 11:06
Thanks, in this case I should use `Element#setAttribute`. This way I can do what I want.

In this case; Is `Element#setProperty` expected to not work or is it a bug?

**Comment by DiegoCardoso** [comment] 2020-05-15 11:11
It works as expected. I will close this issue, as it is not a bug.

**Closed by DiegoCardoso** 2020-05-15 11:11 UTC
