### ISSUE TITLE
Create a prototype of using DataView API with CheckboxGroup

### ISSUE THREAD

**Issue by mshabarov** [vaadin/vaadin-checkbox-flow#142] opened 2020-05-07 07:49 UTC
### Acceptance criteria:
- Use DataView API from vaadin/flow#8267 in `feature/dataprovider` branch and apply it to Vaadin CheckboxGroup component.
- Validate the proposed design for this common used non-lazy component.

**Comment by pleku** [comment] 2020-05-07 08:15
Closing due to misunderstanding, duplicate of https://github.com/vaadin/vaadin-checkbox-flow/issues/141

**Closed by pleku** 2020-05-07 08:15 UTC
