### ISSUE TITLE
Checkbox to boolean binding no longer seems to work in rc5

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-checkbox-flow#60] opened 2018-06-26 10:20 UTC
@davidm76 commented on [Thu Jun 21 2018](https://github.com/vaadin/platform/issues/212)

In our in-house project, binding of a Checkbox to a boolean bean property no longer seems to work.

I have an old copy of the bakery starter project based on 10.0.0.beta3.

I added a boolean field called `archived` to the `User` entity:

```
  public boolean isArchived() { 
    return archived; 
  } 
 
  public void setArchived(boolean archived) { 
    this.archived = archived; 
  } 
 
  private boolean archived; 
```

I added a checkbox to user-form.html:

```
  <vaadin-checkbox id="archived">Archived</vaadin-checkbox> 
```

Then in UserForm.java I added the checkbox and a binding:

```
  @Id("archived")
  private Checkbox archived; 
```
and in `setBinder()` I added a new binding for the new field:

```
binder.bind(archived, "archived");
```

This works as expected and I can edit a user and set and Unser the `archived` property.
See below:
![binder_working_beta2](https://user-images.githubusercontent.com/6536626/41725707-642cdde2-7568-11e8-8003-ee35f47df3cd.gif)

Now, if I do the same with the latest starter, based on rc5, you'll notice that the `archived` checkbox is not being set when the dialog is re-opened:
![binding_not_working_rc5](https://user-images.githubusercontent.com/6536626/41726562-5616ed9a-756a-11e8-91eb-068646f2eebb.gif)

I've attached the projects referenced above:
[vaadin-bakery-app_beta3_working.zip](https://github.com/vaadin/platform/files/2124132/vaadin-bakery-app_beta3_working.zip)

[my-starter-project_rc5_not_working.zip](https://github.com/vaadin/platform/files/2124124/my-starter-project_rc5_not_working.zip)

Thanks.

David.

**Comment by caalador** [comment] 2018-06-26 11:15
Testing on the starter project_rc5 the issue is there, but as a side one can note that if you check the checkBox to true and save, then the next time you open the dialog and the checkbox is NOT checked and click cancel it asks if you want to discard the changes... of which there is only the unchecked checkbox.

**Comment by denis-anisimov** [comment] 2018-07-27 12:37
I would highly recommend do not ever create such kind of tickets.
This is not a ticket.
This is a _story_ which is OK for forum but absolutely not OK for issue tracker.

The application in the example contains thousands line of code and it's absolutely not obvious where is a bug and there is no any proof that the bug is inside Flow and not in the application business logic.

Any bug should prove via its description that this is a project bug but not an application bug.
This description doesn't provide any proof.
As a result I spent significant time to find the exact reason of the behavior and what is the cause of it.
This work should have been done by the submitter.
Only this way allows to make sure that there is an issue in the product.
So every ticket should be localized and contains only relevant lines of code and not thousand lines of code which are unrelated.

This is the localized version of this bug: #4304.

I'm closing this ticket as a duplicate.

**Closed by denis-anisimov** 2018-07-27 12:37 UTC
Labels: bug

**Comment by denis-anisimov** [comment] 2018-07-27 13:16
This is the short description of the bug which consist only of few lines of code instead of huge project with thousand lines of unrelated code:
https://github.com/vaadin/flow/issues/4304#issuecomment-408414862

**Comment by Legioth** [comment] 2018-08-07 08:04
This is probably a more verbose description of the situation described in https://github.com/vaadin/vaadin-checkbox-flow/issues/70, which in turn is fixed but not yet released right now.
